страница групп (есть проблема с редактированием группы)
HimmelSpark/lingvomake pull request #6
Opened 2019-05-05 16:53 UTC by HimmelSpark

после редактирования группы новые данные не сохраняются

2019-05-06 09:59 UTC, supreme2302 requested changes

2019-05-06 09:59 UTC, supreme2302 commented on src/router/guards/groupsGuard.js
> +				  .catch(() => next('/registration?authError=true'))
Если произошла ошибка при загрузке групп - это не значит, что мы не авторизованы. Иначе мы бы свалились еще при загрузке курсов. Тут если и обрабатывать как то ошибку, то наверно не редиректом. Произойдет следующее: нас редиректнет на логин, но т.к. мы авторизованы, нас еще раз редиректнет на dashboard. В-общем хз пока, что вставить в этот блок, но редирект здесь не нужен. Он должен быть только на самом первом промисе.

2019-05-06 09:59 UTC, supreme2302 commented on src/store/modules/unit/state.js
> +  units: [
Костя вроде сделал метод получения всех юнитов. Наверно уже можно дергать его. Но как по мне сомнительная тема). С чем такой подход связан? Там было сложно реализовать получение по id курса?

2019-05-06 10:04 UTC, supreme2302 commented
> после редактирования группы новые данные не сохраняются

2019-05-06 10:04 UTC, supreme2302 commented
> > после редактирования группы новые данные не сохраняются
Связано с беком?

2019-05-07 13:56 UTC, supreme2302 requested changes

2019-05-07 13:56 UTC, supreme2302 commented on src/views/Groups.vue
> +                      @click="editGroup">
Надо задизейблить кнопку, если не все поля заполнены. При создании группы тоже. Наверно даже в рамках данного pr.

2019-05-07 13:56 UTC, supreme2302 commented on src/views/Groups.vue
> +      <v-dialog max-width="390" v-model="deleteGroupModal">
**Предлагаю придерживаться следующего дизайна в модалке удаления чего-либо.**
`<v-dialog v-model="deleteGroupModal" persistent max-width="440">`
`      <v-card>`
`        <v-card-title class="headline">`
`          Do you want to delete this group?`
`        </v-card-title>`
`        <v-card-text>`
`          This process is irreversible, you can't restore this group later!`
`        </v-card-text>`
`        <v-card-actions>`
`          <v-spacer></v-spacer>`
`          <v-btn color="warning" flat @click="deleteGroupModal = false">`
`            Cancel`
`          </v-btn>`
`          <v-btn color="error" flat @click="deleteGroup">`
`            Delete`
`          </v-btn>`
`        </v-card-actions>`
`      </v-card>`
`    </v-dialog>`

**Можешь прямо копировать код и вставлять.**

2019-05-07 13:56 UTC, supreme2302 commented on src/views/Groups.vue
> +	    editGroupModal: false,
Давай я перед мержем реформатну код. После всех исправлений.

2019-05-08 05:07 UTC, HimmelSpark commented on src/router/guards/groupsGuard.js
> +				  .catch(() => next('/registration?authError=true'))
Пока уберу внутренние catch блоки, там никаких ошибок быть не может, по идее, а если что-то произойдет, то попадем во внешний catch

2019-05-08 05:08 UTC, HimmelSpark commented on src/store/modules/unit/state.js
> +  units: [
а я и так дергаю) просто забыл убрать замоканные данные, вроде как

2019-05-08 05:43 UTC, HimmelSpark commented on src/views/Groups.vue
> +                      @click="editGroup">
Предлагаю отложить этот вопрос на другой ПР, я нашел кучу вариантов валидации, нам надо будет выбрать более подходящий

2019-05-08 05:44 UTC, HimmelSpark commented on src/views/Groups.vue
> +      <v-dialog max-width="390" v-model="deleteGroupModal">
```
<v-dialog v-model="deleteGroupModal" persistent max-width="440">
<v-card>
<v-card-title class="headline">
Do you want to delete this group?
</v-card-title>
<v-card-text>
This process is irreversible, you can't restore this group later!
</v-card-text>
<v-card-actions>
<v-spacer></v-spacer>
<v-btn color="warning" flat @click="deleteGroupModal = false">
Cancel
</v-btn>
<v-btn color="error" flat @click="deleteGroup">
Delete
</v-btn>
</v-card-actions>
</v-card>
</v-dialog>
```

2019-05-08 05:45 UTC, HimmelSpark commented on src/views/Groups.vue
> +      <v-dialog max-width="390" v-model="deleteGroupModal">
```
<v-dialog v-model="deleteGroupModal" persistent max-width="440">
        <v-card>
          <v-card-title class="headline">
            Do you want to delete this group?
          </v-card-title>
          <v-card-text>
            This process is irreversible, you can't restore this group later!
          </v-card-text>
          <v-card-actions>
            <v-spacer></v-spacer>
            <v-btn color="warning" flat @click="deleteGroupModal = false">
              Cancel
            </v-btn>
            <v-btn color="error" flat @click="deleteGroup">
              Delete
            </v-btn>
          </v-card-actions>
        </v-card>
      </v-dialog>
```

2019-05-08 05:46 UTC, HimmelSpark commented on src/views/Groups.vue
> +      <v-dialog max-width="390" v-model="deleteGroupModal">
если обернуть код в ``` то табуляция сохраняется)

2019-05-08 05:48 UTC, HimmelSpark commented on src/views/Groups.vue
> +      <v-dialog max-width="390" v-model="deleteGroupModal">
А мне нравится мой дизайн. Именно благодаря тому, что можно цвета формы задавать: в данном случае красный, бросается в глаза, понятно, что что-то серьезное

2019-05-08 05:51 UTC, HimmelSpark commented on src/views/Groups.vue
> +	    editGroupModal: false,
Давай

2019-05-08 05:51 UTC, merged

2019-05-08 05:52 UTC, HimmelSpark commented
Бл*** я забыл запушить перед мержем 😬